services:
  # ... (service redis inchangé)
  redis:
    image: redis:7.2-alpine
    container_name: agentic_forge_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6378
    ports:
      - "${REDIS_HOST_PORT:-6378}:6378"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "-p", "6378", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - agentic_network

  # Serveur FastMCP principal
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_forge_server
    ports:
      - "${HOST_PORT:-8080}:8080"
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/usr/src/app/workspace
      - /usr/src/app/node_modules
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6378
      - DOCKER=true
      - HOST_PROJECT_PATH=${PWD}
    restart: unless-stopped
    command: sh -c "pnpm run build && pnpm run start"
    # --- CORRECTION ---
    # Remplacement de 'wget' par 'curl' qui est plus commun dans les images de base.
    # L'option -f fait en sorte que curl retourne un code d'erreur en cas d'échec HTTP (ex: 404, 500).
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # --- FIN DE LA CORRECTION ---
    networks:
      - agentic_network

  # ... (services web et worker inchangés)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_forge_web
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - ./public:/usr/src/app/public
    depends_on:
      server:
        condition: service_healthy
    env_file: .env
    environment:
      - NODE_ENV=production
      - WEB_PORT=3000
      - MCP_SERVER_URL=http://server:8080/mcp
    restart: unless-stopped
    command: pnpm run start:web
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - agentic_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_forge_worker
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/usr/src/app/workspace
      - /usr/src/app/node_modules
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6378
      - DOCKER=true
      - HOST_PROJECT_PATH=${PWD}
    restart: unless-stopped
    command: sh -c "pnpm run build && pnpm run start:worker"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'node -r tsconfig-paths/register dist/worker.js' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - agentic_network

volumes:
  redis_data:
    driver: local

networks:
  agentic_network:
    driver: bridge
    name: agentic_forge_network