services:
  redis:
    image: redis:7.2-alpine
    container_name: agentic_forge_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6378
    ports:
      - "${REDIS_HOST_PORT:-6378}:6378"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "-p", "6378", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - agentic_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_forge_server
    ports:
      - "${HOST_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/usr/src/app/workspace
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    restart: unless-stopped
    # CORRECTION : La commande se contente de lancer le serveur.
    # L'installation est désormais gérée par le Dockerfile.
    command: pnpm run start
    networks:
      - agentic_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_forge_web
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      - server
    env_file: .env
    restart: unless-stopped
    # CORRECTION : La commande se contente de lancer le serveur web.
    command: pnpm run start:web
    networks:
      - agentic_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_forge_worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/usr/src/app/workspace
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    restart: unless-stopped
    # CORRECTION : La commande se contente de lancer le worker.
    command: pnpm run start:worker
    networks:
      - agentic_network

volumes:
  redis_data:
    driver: local

networks:
  agentic_network:
    driver: bridge
    name: agentic_forge_network